; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.31"

; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[mediacommons_profile][download][type] = "git"
projects[mediacommons_profile][download][url] = "https://github.com/lhenze/mediacommons-install-profile"
projects[mediacommons_profile][type] = "profile"

; Modules
projects[admin_menu][version] = "3.0-rc4"

projects[advanced_help][version] = "1.1"

projects[backup_migrate][version] = "3.0"

projects[better_exposed_filters][version] = "3.0-beta4"

projects[ctools][version] = "1.4"

projects[coffee][version] = "2.0"

projects[cnr][version] = "4.22"

projects[date][version] = "2.8"

projects[devel][version] = "1.5"

projects[diff][version] = "3.2"

projects[ds][version] = "2.6"

projects[email][version] = "1.3"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[entity_view_mode][version] = "1.0-rc1"

projects[entityreference][version] = "1.1"

projects[features][version] = "2.2"
projects[features_extra][version] = "1.0-beta1"
projects[field_group][subdir] = "patched"
projects[field_group][version] = "1.4"

projects[imagefield_crop][version] = "1.1"

projects[link][version] = "1.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[mc_footer][download][type] = "git"
projects[mc_footer][download][url] = "https://github.com/lhenze/mc_footer.git"
projects[mc_footer][type] = "module"
projects[mc_footer][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[mc_global_nav][download][type] = "git"
projects[mc_global_nav][download][url] = "https://github.com/lhenze/mc_global_nav.git"
projects[mc_global_nav][type] = "module"
projects[mc_global_nav][version] = "1.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[mc_hub_and_spoke][download][type] = "git"
projects[mc_hub_and_spoke][download][url] = "https://github.com/lhenze/mc_hub_and_spoke.git"
projects[mc_hub_and_spoke][type] = "module"
projects[mc_hub_and_spoke][version] = "1.7"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[mediacommons_profile2][download][type] = "git"
projects[mediacommons_profile2][download][url] = "https://github.com/lhenze/mediacommons_profile2.git"
projects[mediacommons_profile2][type] = "module"
projects[mediacommons_profile2][version] = "1.2"

projects[menu_token][version] = "1.0-beta5"

projects[references][subdir] = "contrib"
projects[references][version] = "2.1"

projects[pathauto][version] = "1.2"

projects[profile2][version] = "1.3"

projects[realname][version] = "1.2"

projects[simplehtmldom][version] = "1.12"

projects[strongarm][version] = "2.0"

projects[telephone][version] = "1.0-alpha1"

projects[token][version] = "1.5"

projects[url][version] = "1.0"

projects[views][version] = "3.8"

; Themes
projects[rubik][version] = "4.1"

projects[tao][version] = "3.1"

projects[zen][version] = "5.5"

; Modules
projects[imagefield_crop_extended][type] = "module"
projects[imagefield_crop_extended][download][type] = "git"
projects[imagefield_crop_extended][download][url] = "https://github.com/lhenze/imagefield_crop_extended.git"
projects[imagefield_crop_extended][download][revision] = "2b292fd357e1be63054f80e9ec2f437b421aaaa7"


; Themes
projects[mediacommons][type] = "theme"
projects[mediacommons][download][type] = "git"
projects[mediacommons][download][url] = "https://github.com/lhenze/mediacommons"
projects[mediacommons][download][revision] = "2269a82f14337e52a746cb1ec11703b5d4eabe96"

